Repository mongodb/js-bson, pull requests merged in 2022-06, with the labels that each got.

#500 fix(NODE-4211): Do not require crypto in browser builds
  package-lock.json
  package.json
  rollup.config.js
  src/parser/utils.ts
Labels: tracked-in-jira, Team Review

#501 fix(NODE-4302): remove downlevel ts and typesVersions
  .evergreen/config.yml
  .evergreen/init-nvm.sh
  .evergreen/install-dependencies.sh
  .evergreen/run-typescript.sh
  package-lock.json
  package.json
Labels: Primary Review

#504 docs(NODE-4349): add note about Binary(string) behavior
  src/binary.ts
Labels: Team Review
